- name: check a number less than 10 or not
  hosts: localhost
  connection: local
  vars:
    NUMBER_OF_SESSIONS: 7
  tasks:
    - name: is ansible more than 5 sessions
      ansible.builtin.debug:
        msg: "yes, more than 5 sessions"
      when: NUMBER_OF_SESSIONS >= 7